local addonName, addon = ...

addon.ALLIANCE_MAP_ID = 2352

addon.AllianceRiddles = {
    {riddle = "Stone laid by lost hands. His name swallowed by the tide. Look where lilies listen.", x = 63.2, y = 38.3, item = "Sturdy Wooden Bookcase"},
    {riddle = "Sentinel of stone. First to greet each new neighbor. Seek out the deep shade.", x = 58.1, y = 30.1, item = "Sturdy Wooden Shelf"},
    {riddle = "Clouds bow to the stone. Heights where gryphons dare not fly. Above all, it waits.", x = 69.2, y = 26.7, item = "Sturdy Wooden Interior Door"},
    {riddle = "Highland rime meets mists. Gateway to the dusky wood. The dead point the way.", x = 63.1, y = 46.7, item = "Goldshire Window"},
    {riddle = "Stone eye scans the shade. Forest breathes beneath its gaze. Look to the lone pine.", x = 64.8, y = 50.9, item = "Tall Sturdy Wooden Bookcase"},
    {riddle = "No leaves, yet it blooms. Still limbs cradle gentle glows. Wade where violet grows.", x = 59.8, y = 52.4, item = "Sturdy Wooden Chair"},
    {riddle = "Fireflies glow and flit. Falls feed the whispering wood. The drowned cave awaits.", x = 66.9, y = 57.0, item = "Stormwind Interior Narrow Wall"},
    {riddle = "Names worn down by time. Stone weeps where the water sings. Drop a coin, then dig.", x = 58.3, y = 65.0, item = "Stormwind Interior Doorway"},
    {riddle = "Trellis frames the torch. A seat above misty shores. Seek the ledge below.", x = 52.8, y = 66.8, item = "Stormwind Interior Wall"},
    {riddle = "Tribute to the lost. Where seaspray climbs ancient cliffs. A lonely bell tolls.", x = 55.3, y = 71.3, item = "Sturdy Wooden Bench"},
    {riddle = "Salt clings to old wood. Crow's nests watch the tide retreat. A cave holds secrets.", x = 61.6, y = 79.4, item = "Wicker Basket"},
    {riddle = "A weary roof sighs. Ships rot just beyond the reach. Look beneath the bow.", x = 54.2, y = 73.6, item = "Reinforced Wooden Chest"},
    {riddle = "Across from the bight. The oyster shuckers have gone. Search the lonely dock.", x = 64.5, y = 85.6, item = "Iron-Reinforced Cupboard"},
    {riddle = "Awnings span river's flow. Gold to the west, darkness east. Look beneath stunted tree.", x = 47.7, y = 61.9, item = "Stormwind Beam Platform"},
    {riddle = "Pale moonlight rises. Wisps guard what the dusk holds dear. Look where roots rise up.", x = 49.9, y = 56.6, item = "Stormwind Round Platform"},
    {riddle = "Aboveground tunnel. Lights mark where life's blood once flowed. Look atop the falls.", x = 54.9, y = 50.6, item = "Stormwind Large Platform"},
    {riddle = "Water flows below. While fresh cider flows above. Dig where the wheel churns.", x = 46.3, y = 58.0, item = "Small Wooden Stool"},
    {riddle = "Below autumn soil. Gargled seaweed and dead fish. Stone mouth drinks the sea.", x = 45.4, y = 64.4, item = "Small Wooden Nightstand"},
    {riddle = "Cows low in their pen. Leaves fall on the roundabout. Treasure waits within.", x = 40.8, y = 61.3, item = "Carved Wooden Crate"},
    {riddle = "Small farmer's homestead. Where cows bask in golden light. Dig between the rows.", x = 39.1, y = 59.9, item = "Tall Sturdy Wooden Chair"},
    {riddle = "Light sweeps open sea. A beacon upon the bluff. Look behind its back.", x = 33.9, y = 72.8, item = "Short Wooden Cabinet"},
    {riddle = "Blades turn in the wind. Amber leaves drift toward the sea. Check beneath the stairs.", x = 34.6, y = 60.2, item = "Three-Candle Wrought Iron Chandelier"},
    {riddle = "Hollow nurse log yawns. Waters reflect gold above. Dry leaves hide riches.", x = 36.6, y = 57.8, item = "Wrought Iron Floor Lamp"},
    {riddle = "Harvest hangs from boughs. Crimson against autumn gold. Trust the lantern's light.", x = 36.6, y = 54.2, item = "Wrought Iron Chandelier"},
    {riddle = "Prism of the cove. Where worn stone endures the roar. Dive deep to prevail.", x = 37.1, y = 45.9, item = "Wooden Chamberstick"},
    {riddle = "Beneath gryphon wings. On the small aerie's low slopes. Find the broken tree.", x = 42.6, y = 53.8, item = "Sturdy Wooden Bed"},
    {riddle = "Covered connection. Over the lilied waters. Search the banks below.", x = 42.5, y = 44.7, item = "Covered Wooden Table"},
    {riddle = "Beyond smugglers cove. Wrecks hide a sunken saloon. Look for the good stuff.", x = 61.0, y = 82.0, item = "Sturdy Fireplace"},
    {riddle = "Watcher on the shore. Where ships drop anchor and make berth. Look where crabs scuttle.", x = 29.8, y = 48.4, item = "Wide Charming Couch"},
    {riddle = "Gulls scream for free meals. Salt clings to fishmonger scales. Seek the barnacles.", x = 28.5, y = 44.8, item = "Iron-Reinforced Standing Mirror"},
    {riddle = "Boardwalk lies broken. Sand bars cradle what remains. Seek out the lone plank.", x = 28.3, y = 40.1, item = "Carved Wooden Bar Table"},
    {riddle = "An old flag flutters. A platform grants ocean views. Look below the stairs.", x = 26.2, y = 37.9, item = "Large Covered Wooden Table"},
    {riddle = "Outside outer banks. Where crabs claim an island shore. Sift through the driftwood.", x = 21.0, y = 30.0, item = "Large Sturdy Wooden Table"},
    {riddle = "Stairs snake up the bluffs. A pier juts over shallows. Seek the shade below.", x = 29.0, y = 28.1, item = "Charming Couch"},
    {riddle = "A lone flag flutters. Covered bridge over dry ground. Sift the sand beneath.", x = 30.9, y = 31.1, item = "Elegant Table Lamp"},
    {riddle = "Petals sway in the breeze. Wooden arms sweep floral scents. Look where pink meets gold.", x = 36.9, y = 32.8, item = "Bel'ameth Interior Wall"},
    {riddle = "Twin silos stand watch. Meandering rows slumber. Search among the rocks.", x = 39.9, y = 32.0, item = "Bel'ameth Round Interior Pillar"},
    {riddle = "Vines climb the hillside. Their yield crushed in tubs of wood. Look where juice stains earth.", x = 40.9, y = 28.3, item = "Bel'ameth Interior Doorway"},
    {riddle = "Cool waters, unfed. Still against blue sky and green. Sheltered by the cliff.", x = 49.1, y = 27.1, item = "Bel'ameth Beam Platform"},
    {riddle = "Lush trees grow skyward. A stream threads through leafy glades. Look where waters churn.", x = 49.7, y = 42.5, item = "Bel'ameth Round Platform"},
    {riddle = "Seek the smallest house. Where pawsteps mark the sand. Now dig where dogs lie.", x = 53.6, y = 41.9, item = "Bel'ameth Large Platform"},
    {riddle = "Six sides, but no walls. Afloat above chill waters. Secrets wait below.", x = 52.0, y = 29.0, item = "Ornate Stonework Fireplace"},
    {riddle = "Azure and gold sway. While beneath pretenders play. Investigate stage left.", x = 57.3, y = 39.2, item = "Gemmed Elven Chest"},
    {riddle = "Earth, fire, smoke, and steam. Blade or plow, the shaper's choice. Look where metals bend.", x = 53.6, y = 39.7, item = "Small Elegant Padded Chair"},
    {riddle = "Mushrooms mark the ring. Deep within the shadowed wood. Dig where fireflies swarm.", x = 60.3, y = 56.8, item = "Grand Elven Bookcase"},
    {riddle = "Where trees have no roots. A gate has no door or hinge. Will call for treasure.", x = 55.0, y = 40.0, item = "Circular Elven Table"},
    {riddle = "Arcane power thrums. Journey home with a mere step. Dig beside the roost.", x = 56.6, y = 27.5, item = "Elegant Padded Chaise"},
    {riddle = "Where roses are red. The perfect venue awaits. Throw some rice, then dig.", x = 57.7, y = 42.0, item = "Elegant Elven Desk"},
    {riddle = "Cart lost in the dark. Growth consumes all that remains. Search beside the road.", x = 56.8, y = 52.3, item = "Elven Floral Window"},
    {riddle = "Near the twilit wood. Falls give a cave's mouth its roar. Look beneath the torch.", x = 59.0, y = 45.7, item = "Elegant Padded Footstool"},
}
