local addonName, addon = ...

addon.HORDE_MAP_ID = 2351

addon.HordeRiddles = {
    {riddle = "Between mighty tusks. A doorway shimmers and hums. Look where the carts park.", x = 53.5, y = 50.0, item = "Orgrimmar Interior Doorway"},
    {riddle = "Two towers stand guard. Worn bridge spans the falls below. Go smell some flowers.", x = 55.6, y = 49.9, item = "Orgrimmar Interior Wall"},
    {riddle = "Though it may have leaks. Wooden wall diverts the stream. Check the ledge below.", x = 56.4, y = 47.9, item = "Orgrimmar Round Interior Pillar"},
    {riddle = "Back steps to the wood. Above needled canopy. Stop halfway and search.", x = 58.0, y = 48.9, item = "Rugged Stool"},
    {riddle = "Three falls feed the flows. Fishers hunt with spear and trap. Look below the traps.", x = 63.5, y = 44.7, item = "Iron Chain Chandelier"},
    {riddle = "Six tables are dressed. Conifers observe the feast. Compliment the chef.", x = 62.2, y = 48.9, item = "Iron-Reinforced Door"},
    {riddle = "Mist threads through the pines. Sellers ring the roundabout. Search the succulents.", x = 62.6, y = 51.6, item = "Iron-Studded Wooden Window"},
    {riddle = "From sagging rope bridge. Torches mark a steep descent. Search the water's edge.", x = 72.0, y = 50.0, item = "Orgrimmar Chair"},
    {riddle = "Cedar scents the air. Where kneaded muscles soak deep. Search between the tubs.", x = 68.9, y = 52.5, item = "Rugged Brazier"},
    {riddle = "Platform high above. At the edge of sea and wood. Look where the lights sway.", x = 72.1, y = 41.8, item = "Orgrimmar Nightstand"},
    {riddle = "Through an arch of bone. A stream cradles what once moved. Search the vertebrae.", x = 60.7, y = 64.5, item = "Durable Wooden Chest"},
    {riddle = "Near the scorching songs. Arbor frames the setting sun. Dig beyond the vows.", x = 38.6, y = 80.2, item = "Orgrimmar Beam Platform"},
    {riddle = "Below the towers. Townsfolk guarded from the spray. Dig in awning's shade.", x = 55.5, y = 52.4, item = "Orgrimmar Round Platform"},
    {riddle = "Below forest deck. Secret straw-floored writer's nook. Seek the wheelbarrow.", x = 63.7, y = 56.2, item = "Orgrimmar Large Platform"},
    {riddle = "Deep in the forest. Where the hookah haze rises. Treasure waits below.", x = 64.6, y = 58.0, item = "High-Backed Orgrimmar Chair"},
    {riddle = "Where the desert blooms. Fire burns at circle's center. Look to the shadows.", x = 57.7, y = 63.4, item = "Short Orgrimmar Bench"},
    {riddle = "Wave-swept sandy knoll. Follow the bridge to nowhere. Dig among the palms.", x = 68.3, y = 68.9, item = "Iron-Reinforced Crate"},
    {riddle = "Seagulls await ships. Tower watches, fountain spits. Look where wyverns perch.", x = 68.1, y = 75.7, item = "Large Orgrimmar Bookcase"},
    {riddle = "One boardwalk above. A second boardwalk below. Search near the canoes.", x = 64.8, y = 73.0, item = "Short Orgrimmar Bookcase"},
    {riddle = "Nature carved a gate. Sea and sand mingle below. Search atop the arch.", x = 61.8, y = 78.4, item = "Tusked Candleholder"},
    {riddle = "Two huts crowd the isle. Beach grass sways in the sea breeze. Swim with the starfish.", x = 63.2, y = 92.5, item = "Horned Hanging Sconce"},
    {riddle = "Wooden mask tends bar. Pineapples lift the spirits. Dig near the fire pit.", x = 58.0, y = 86.2, item = "Spiky Banded Barrel"},
    {riddle = "Boasting two bridges. Isle's lone palm leans toward the shore. Search the coconuts.", x = 58.0, y = 79.9, item = "Horned Banded Barrel"},
    {riddle = "Sea's greatest hunter. Hanging in the salted air. Search below the deck.", x = 53.8, y = 82.0, item = "Crude Banded Crate"},
    {riddle = "Hot air fills the canvas. Where boardwalk crowns stoney arch. Look where paths cross.", x = 52.1, y = 81.8, item = "Small Orgrimmar Chair"},
    {riddle = "Salt and sky collide. Tower guards the fisher's catch. Dig at the front steps.", x = 53.4, y = 84.6, item = "Razorwind Storage Table"},
    {riddle = "Oceanside ravine. Pirate camp awaits above. Anchor marks the spot.", x = 50.3, y = 83.0, item = "Hide-Covered Wall Shelf"},
    {riddle = "Seek the bone tunnel. In sight of a broken hull. Trace the sunken chain.", x = 47.8, y = 88.6, item = "Orgrimmar Bureaucrat's Desk"},
    {riddle = "Dead hulk in the tide. A mast lies against the dunes. The crow's nest sees all.", x = 44.2, y = 86.7, item = "Tusked Fireplace"},
    {riddle = "Stone mouth, wooden teeth. Mast as toothpick, should it eat. Go down its gullet.", x = 39.8, y = 72.8, item = "Orgrimmar Tusked Bed"},
    {riddle = "Oasis watcher. Perched above crystal waters. Find the bench below.", x = 42.1, y = 66.3, item = "Razorwind Bar Table"},
    {riddle = "Where palm trees grow thick. Platform sits on stone's old spine. Look to the low flame.", x = 44.0, y = 66.0, item = "Wide Hide-Covered Bench"},
    {riddle = "Old watering hole. Take a swing or take a dive. Hold your breath and dig.", x = 42.4, y = 50.4, item = "Razorwind Wall Mirror"},
    {riddle = "Down below the bluffs. Water flows below stone bridge. Dive to the shipwreck.", x = 51.6, y = 82.6, item = "Long Orgrimmar Bench"},
    {riddle = "From atop the falls. Stargazers peer past the palms. Dig through their notes.", x = 45.2, y = 56.3, item = "Lovely Elven Shelf"},
    {riddle = "Where clear waters churn. The earth opens wide to breathe. What waits in its maw?", x = 45.4, y = 57.3, item = "Silvermoon Round Interior Pillar"},
    {riddle = "Oasis bears fruit. Seek not the greens, but purple. Harvest at center.", x = 47.1, y = 59.6, item = "Silvermoon Interior Wall"},
    {riddle = "Steam bursts toward the sky. Blue pools swirl with ancient heat. Look for the tether.", x = 51.7, y = 72.7, item = "Silvermoon Interior Doorway"},
    {riddle = "Penned in desert bloom. Loyal steeds water and feed. Needles in haystacks.", x = 59.0, y = 73.7, item = "Silvermoon Large Platform"},
    {riddle = "Three huts in spire's shade. Wooden overlook curves out front. Search near a planter.", x = 64.5, y = 69.1, item = "Silvermoon Round Platform"},
    {riddle = "Where kodos take rest. Past gate marked with bone and fire. Dig near the hay bale.", x = 57.8, y = 59.0, item = "Silvermoon Beam Platform"},
    {riddle = "Just like Thunder Bluff. Tower watches three swaying paths. Look to the platform.", x = 50.3, y = 76.8, item = "Elegant Elven Chandelier"},
    {riddle = "Near where farmers toil. Beast of burden raises young. Seek the broadest shade.", x = 50.8, y = 61.5, item = "Open Elegant Elven Barrel"},
    {riddle = "Overlooking fields. Bushels brim with bloom and seed. Check for stock in back.", x = 49.5, y = 59.9, item = "Elegant Padded Chair"},
    {riddle = "Highest wyvern perch. Circling above the sea. Look to the center.", x = 50.9, y = 89.6, item = "Carved Elven Bookcase"},
    {riddle = "Across gentle falls. Bridge broken, chains given way. Look to the east end.", x = 43.2, y = 69.4, item = "Elegant Almond Table"},
    {riddle = "Smugglers scheme above. Tortollans tend bar below. Search through the seaweed.", x = 39.2, y = 74.0, item = "Elegant Padded Divan"},
    {riddle = "A secret beast den. Hidden behind narrow falls. Search the oasis.", x = 39.4, y = 57.6, item = "Elegant Wooden Dresser"},
    {riddle = "The fire never ends. Gather for sorrow or mirth. Search behind the fuel.", x = 39.8, y = 78.7, item = "Elegant Curved Table"},
    {riddle = "Life stirs from dry soil. Camp where fishers may take rest. Fire warms the treasure.", x = 58.0, y = 69.0, item = "Small Elegant End Table"},
}
